version: '3.3'

services:
  csharp:
    container_name: "csharp"
    image: "csharp:dev"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - PRIVATE_KEY=LXycaMpw5BzgfhsS4ydNxGzJ36qMnPrQHI8u2x3wQCZCZyGtZ4sOQbkEWnHmVchZEa79a0Y3xK7IKCymSLkugyabbJUGuXfyuoKL
      - PUBLIC_KEY=mIhuoMJh0jbA5W4pUUNK
      - PROTO=http://