version: '3'

volumes:
  thor-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: [Directory taht will house local storage for THOR] Example: /Users/tbutler/Dev/thor-data

services:
  csharp:
    container_name: "csharp"
    image: "csharp:dev"
    ports:
      - 8091:80
    environment:
      - PRIVATE_KEY=LXycaMpw5BzgfhsS4ydNxGzJ36qMnPrQHI8u2x3wQCZCZyGtZ4sOQbkEWnHmVchZEa79a0Y3xK7IKCymSLkugyabbJUGuXfyuoKL
      - PUBLIC_KEY=mIhuoMJh0jbA5W4pUUNK
      - APP_SETTINGS=./config/dev.cfg
      - BASE_URL=http://$DOCKER_IP
      - PROTO=http://
      - WIDGET_URL_PREFIX=/ic/widget1/
    network_mode: bridge

  thor:
    container_name: "thor"
    image: "quay.io/lumavate/thor:2.0"
    ports:
      - 80:4201
      - 443:4202
    volumes:
      - thor-data:/data:rw
      - [Root Directory that house your local components followed by ':/components/custom:rw'] Example: /Users/tbutler/Dev/components:/components/custom:rw
    environment:
      - PUBLIC_KEY=mIhuoMJh0jbA5W4pUUNK
      - PRIVATE_KEY=LXycaMpw5BzgfhsS4ydNxGzJ36qMnPrQHI8u2x3wQCZCZyGtZ4sOQbkEWnHmVchZEa79a0Y3xK7IKCymSLkugyabbJUGuXfyuoKL
      - HOST_IP=$DOCKER_IP
    network_mode: bridge
